export enum StudyType {
    ARTICLE = "ARTICLE",
    BOOK = "BOOK",
    BOOKLET = "BOOKLET",
    INBOOK = "INBOOK",
    INCOLLECTION = "INCOLLECTION",
    INPROCEEDINGS = "INPROCEEDINGS",
    MANUAL = "MANUAL",
    MASTERSTHESIS = "MASTERSTHESIS",
    MISC = "MISC",
    PHDTHESIS = "PHDTHESIS",
    PROCEEDINGS = "PROCEEDINGS",
    TECHREPORT = "TECHREPORT",
    UNPUBLISHED = "UNPUBLISHED"
  }